network:
  version: 1
  config:
  - type: physical
    name: eth0
    mac_address: ${ip_mac}
    subnets:
     - type: static
       address: ${ip_config}
       gateway: 192.168.1.1
       netmask: 255.255.255.0
     -  type: nameserver
        address:
        - 8.8.8.8
        - 8.8.4.4
