#cloud-config
hostname: ${hostname}
ssh_authorized_keys:
  - ${ssh_key}
resize_rootfs: true
package_update: true
package_upgrade: true
packages:
  - htop
users:
  - default
  - name: debian
    gecos: Debian
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
system_info:
  default_user:
    name: debian
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
runcmd:
  - sudo su -c "echo localhost ${hostname} >> /etc/hosts"
  - sudo su -c 'echo -e "\nauto eth0 \niface eth0 inet static \n         address ${ip_config} \n         netmask 255.255.255.0 \n         network 192.168.1.0 \n         broadcast 192.168.1.255 \n         gateway 192.168.1.1" >  /etc/network/interfaces.d/50-cloud-init.cfg'
  - sudo su -c "systemctl restart networking"
  - sudo su -c "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
power_state:
  timeout: 5
  mode: reboot

